source /etc/profile.d/git-completion.bash

# colors!
green="\[\033[1;32m\]"
blue="\[\033[1;34m\]"
purple="\[\033[1;35m\]"
yellow="\[\033[1;33m\]"
red="\[\033[1;31m\]"
black="\[\033[1;30m\]"
white="\[\033[1;37m\]"
cyan="\[\033[1;36m\]"
reset="\[\033[0m\]"

# Change command prompt

source /etc/profile.d/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
export PS1="$blue\u$green\$(__git_ps1)$cyan \W $ $reset"

alias txt="/c/Program\ Files/Sublime\ Text/sublime_text.exe"
alias g="/c/Program\ Files/Sublime\ Merge/sublime_merge.exe"

# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi
